-- MASROFI CLEAN INSTALL SAFE - لا يمسح بيانات قديمة
create extension if not exists pgcrypto;
create table if not exists public.profiles (user_id uuid primary key references auth.users(id) on delete cascade, monthly_salary numeric not null default 0, salary_day int not null default 1 check (salary_day between 1 and 28), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.transactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, type text not null check (type in ('income','expense')), amount numeric not null default 0, title text, category text, created_at timestamptz not null default now());
create table if not exists public.bills (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, amount numeric not null default 0, due_date date, is_paid boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.debts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, amount numeric not null default 0, type text not null check(type in ('owe','owed')), is_closed boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.goals (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, target_amount numeric not null default 0, saved_amount numeric not null default 0, created_at timestamptz not null default now());
create table if not exists public.chat_messages (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, body text not null, created_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.transactions enable row level security; alter table public.bills enable row level security; alter table public.debts enable row level security; alter table public.goals enable row level security; alter table public.chat_messages enable row level security;
do $$ declare t text; begin foreach t in array array['profiles','transactions','bills','debts','goals','chat_messages'] loop execute format('drop policy if exists %I on public.%I','owner_all_'||t,t); execute format('create policy %I on public.%I for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid())','owner_all_'||t,t); end loop; end $$;
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
drop trigger if exists trg_profiles_updated_at on public.profiles; create trigger trg_profiles_updated_at before update on public.profiles for each row execute function public.touch_updated_at();
create or replace function public.create_profile_for_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(user_id) values(new.id) on conflict(user_id) do nothing; return new; end $$;
drop trigger if exists on_auth_user_created_masrofi on auth.users; create trigger on_auth_user_created_masrofi after insert on auth.users for each row execute function public.create_profile_for_new_user();
grant usage on schema public to anon, authenticated; grant all on all tables in schema public to authenticated; grant all on all sequences in schema public to authenticated;
